export const SEED_DRINKS = [
  {"code":"ADZLATTE","name":"Adzuki Matcha Latte"},
  {"code":"BARNIE","name":"Barnie By The Daily Juice"},
  {"code":"MARY","name":"Berry Mary"},
  {"code":"CHEEKY","name":"Cheeky Flamingo"},
  {"code":"COCOSHAKE","name":"Coconut Shake"},
  {"code":"COLDBREW","name":"Cold Brew Black Coffee by CSHH"},
  {"code":"BOYLECOFI","name":"Cold Brew Dutch Coffee"},
  {"code":"FLOWERTEA","name":"Cold Brew Flower Tea"},
  {"code":"EATGRASS","name":"Eat Grass by The Daily Juice"},
  {"code":"EVIL","name":"Evil Flamingo"},
  {"code":"GOJUICE","name":"GO! Juice"},
  {"code":"MANUKA","name":"Golden Manuka Cold-Pressed Juice"},
  {"code":"GRAINDEER","name":"Grain Deer"},
  {"code":"NINJA","name":"Green Ninja"},
  {"code":"JUSTPICKED","name":"Just Picked CocoWater"},
  {"code":"KINKY","name":"Kinky Waikiki"},
  {"code":"KRYPTO","name":"Krypto by Daily Juice"},
  {"code":"LANTERN","name":"Lantern"},
  {"code":"LEMO","name":"Lemon, Lime & Ginger Juice"},
  {"code":"APPLEPIE","name":"Liquid Apple Pie"},
  {"code":"LILGINGY","name":"Little Gingy Cold-Pressed Juice"},
  {"code":"MADAME","name":"Madame Grass"},
  {"code":"MLATTE","name":"Matcha Latte"},
  {"code":"MOVE","name":"Move 78"},
  {"code":"COCO","name":"Pink Coconut Water"},
  {"code":"POMO","name":"Pomegranate & Elderflower Juice"},
  {"code":"SHOYUCOFFEE","name":"Shoyu Coffee Latte"},
  {"code":"BONZAI","name":"The Bashful Bonzai"},
  {"code":"HIMALAYAS","name":"The Himalayas Cold-Pressed Juice"}
];
